// Generated by CoffeeScript 1.7.1
module.exports = {
  parse: function(json, cbs) {
    var e, obj;
    if (cbs == null) {
      cbs = null;
    }
    if (cbs) {
      obj = null;
      try {
        obj = JSON.parse(json);
      } catch (_error) {
        e = _error;
        cbs.error(json);
      }
      if (obj) {
        return cbs.success(obj);
      }
    } else {
      return JSON.parse(json);
    }
  }
};

//# sourceMappingURL=utils.map
